theme = "dracula"

[keys.normal.m]
t = "@|~/.config/helix/surround_tag.sh<ret>sxxhelixtagxx<ret>c"
T = "@s\\x3C.+?\\x3E<ret><C-s>,d<C-o>(,d"
r = "@s\\x3C/?\\w*<ret>;<C-s>,ax<esc>miwcxxhelixtagxx<esc><C-o>(,ax<esc>miwcxxhelixtagxx<esc><C-o>sxxhelixtagxx<ret>c"
