theme = "dracula"

[editor.file-picker]
hidden = false

[keys.normal]
"A-/" = "toggle_line_comments"
"Cmd-/" = "toggle_line_comments"

[keys.normal.m]
t = "@|~/.config/helix/surround_tag.sh<ret>sxxhelixtagxx<ret>c"
T = "@s\\x3C.+?\\x3E<ret><C-s>,d<C-o>(,d"
R = "@s\\x3C/?\\w*<ret>;<C-s>,ax<esc>miwcxxhelixtagxx<esc><C-o>(,ax<esc>miwcxxhelixtagxx<esc><C-o>sxxhelixtagxx<ret>c"

[keys.normal.g]
w = ["save_selection", "goto_word"]

[keys.normal.space]
L = ":lsp-restart"
F = "file_picker_in_current_buffer_directory"

[keys.insert]
C-space = "completion"
