[[language]]
name = "javascript"
auto-format = true
formatter = { command = "prettier", args = ["--stdin-filepath", "fake-file.js"] }
language-servers = [ "typescript-language-server", "vscode-eslint-language-server" ]

[[language]]
name = "jsx"
auto-format = true
formatter = { command = "prettier", args = ["--stdin-filepath", "fake-file.jsx"] }
language-servers = [ "typescript-language-server", "vscode-eslint-language-server" ]

[[language]]
name = "typescript"
auto-format = true
formatter = { command = "prettier", args = ["--stdin-filepath", "fake-file.ts"] }
language-servers = [ "typescript-language-server", "vscode-eslint-language-server" ]

[[language]]
name = "tsx"
auto-format = true
formatter = { command = "prettier", args = ["--stdin-filepath", "fake-file.tsx"] }
language-servers = [ "typescript-language-server", "vscode-eslint-language-server" ]
